#include <iostream>
#include <memory.h>
using namespace std;
void city(int pos,int x,int y);
int count=1,a[50][50],wall[50][50][4];
int main()
{
	int m,n,i,j,k,max=0,total=0;
	cin>>m>>n;
	for(i=0;i<m;i++)
		for(j=0;j<n;j++)
		{
			cin>>a[i][j];
            if(a[i][j]==1)
			{
				wall[i][j][0]=0;
				wall[i][j][1]=0;
				wall[i][j][2]=0;
				wall[i][j][3]=1;
			}
			if(a[i][j]==2)
			{
				wall[i][j][0]=1;
				wall[i][j][1]=0;
				wall[i][j][2]=0;
				wall[i][j][3]=0;
			}
			if(a[i][j]==3)
			{
				wall[i][j][0]=1;
				wall[i][j][1]=0;
				wall[i][j][2]=0;
				wall[i][j][3]=1;
			}
			if(a[i][j]==4)
			{
				wall[i][j][0]=0;
				wall[i][j][1]=1;
				wall[i][j][2]=0;
				wall[i][j][3]=0;
			}
			if(a[i][j]==5)
			{
				wall[i][j][0]=0;
				wall[i][j][1]=1;
				wall[i][j][2]=0;
				wall[i][j][3]=1;
			}
			if(a[i][j]==6)
			{
				wall[i][j][0]=1;
				wall[i][j][1]=1;
				wall[i][j][2]=0;
				wall[i][j][3]=0;
			}
			if(a[i][j]==7)
			{
				wall[i][j][0]=1;
				wall[i][j][1]=1;
				wall[i][j][2]=0;
				wall[i][j][3]=1;
			}
			if(a[i][j]==8)
			{
				wall[i][j][0]=0;
				wall[i][j][1]=0;
				wall[i][j][2]=1;
				wall[i][j][3]=0;
			}
			if(a[i][j]==9)
			{
				wall[i][j][0]=0;
				wall[i][j][1]=0;
				wall[i][j][2]=1;
				wall[i][j][3]=1;
			}
			if(a[i][j]==10)
			{
				wall[i][j][0]=1;
				wall[i][j][1]=0;
				wall[i][j][2]=1;
				wall[i][j][3]=0;
			}
			if(a[i][j]==11)
			{
				wall[i][j][0]=1;
				wall[i][j][1]=0;
				wall[i][j][2]=1;
				wall[i][j][3]=1;
			}
			if(a[i][j]==12)
			{
				wall[i][j][0]=0;
				wall[i][j][1]=1;
				wall[i][j][2]=1;
				wall[i][j][3]=0;
			}
			if(a[i][j]==13)
			{
				wall[i][j][0]=0;
				wall[i][j][1]=1;
				wall[i][j][2]=1;
				wall[i][j][3]=1;
			}
			if(a[i][j]==14)
			{
				wall[i][j][0]=1;
				wall[i][j][1]=1;
				wall[i][j][2]=1;
				wall[i][j][3]=0;
			}
			if(a[i][j]==15)
			{
				wall[i][j][0]=1;
				wall[i][j][1]=1;
				wall[i][j][2]=1;
				wall[i][j][3]=1;
			}
			if(a[i][j]==0)
			{
				wall[i][j][0]=0;
				wall[i][j][1]=0;
				wall[i][j][2]=0;
				wall[i][j][3]=0;
			}
			a[i][j]=0;
		}
	for(i=0;i<m;i++)
		for(j=0;j<n;j++)
		{
			if(a[i][j]==0)
			{
				a[i][j]=1;
				total++;
				for(k=0;k<4;k++)
					city(k,i,j);
				if(count>max)
					max=count;
				count=1;
			}
		}
	cout<<total<<endl;
	cout<<max<<endl;
	return 0;
}

void city(int pos,int x,int y)
{
	int i;
	if(pos==0)
	{
		if(wall[x][y][0]==0&&a[x-1][y]==0)
		{
			count++;
			a[x-1][y]=1;
			for(i=0;i<4;i++)
			{
				if(i==2) continue;
				city(i,x-1,y);
			}
		}
	}
	if(pos==1)
	{
		if(wall[x][y][3]==0&&a[x][y-1]==0)
		{
			count++;
			a[x][y-1]=1;
			for(i=0;i<4;i++)
			{
				if(i==3) continue;
				city(i,x,y-1);
			}
		}
	}
	if(pos==2)
	{
		if(wall[x][y][2]==0&&a[x+1][y]==0)
		{
			count++;
			a[x+1][y]=1;
			for(i=0;i<4;i++)
			{
				if(i==0) continue;
				city(i,x+1,y);
			}
		}
	}
	if(pos==3)
	{
		if(wall[x][y][1]==0&&a[x][y+1]==0)
		{
			count++;
			a[x][y+1]=1;
			for(i=0;i<4;i++)
			{
				if(i==1) continue;
				city(i,x,y+1);
			}
		}
	}
}

